Update portability of tools/peek-* python -i shebang usage

diff --git a/apis/python/tools/peek-ann b/apis/python/tools/peek-ann
--- a/apis/python/tools/peek-ann
+++ b/apis/python/tools/peek-ann
@@ -1,43 +1,14 @@
-#!/usr/bin/env python -i
+#!/bin/bash
 
-# Invoke this with, for example,
-#
-#   python -i peek-ann.py anndata/pbmc3k_processed.h5ad
-#
-# -- then you can inspect the anndata object.
+# Simply runs python -i peek-ann.py.
+# That can be done with '#!/usr/bin/env python -i' in the peek-ann.py shebang
+# line, but not all OSes support three words being present in the shebang line.
+us=$(basename $0)
+ourdir=$(dirname $0)
+py=$ourdir/peek-ann.py
+if [ ! -f $py ]; then
+    echo "$us: cannot find $py" 1>&2
+    exit 1
+fi
 
-import sys
-
-import anndata
-import numpy
-import pandas
-import scipy  # noqa: F401
-import tiledb  # noqa: F401
-
-import tiledbsc
-import tiledbsc.io
-
-# module aliases
-ad = anndata
-np = numpy
-pd = pandas
-
-if len(sys.argv) == 1:
-    input_path = "anndata/pbmc-small.h5ad"
-elif len(sys.argv) == 2:
-    input_path = sys.argv[1]
-else:
-    print(f"{sys.argv[0]}: need just one .h5ad file name.", file=sys.stderr)
-    sys.exit(1)
-
-ann = anndata.read_h5ad(input_path)
-decat = tiledbsc.util_ann._decategoricalize
-
-
-# Interact at the prompt now:
-# * ann.X
-# * ann.obs.keys()
-# * ann.obs.head()
-# * ann.obs.index
-# * ann.obs.values
-# * etc
+exec python -i $py "$@"
diff --git a/apis/python/tools/peek-soco b/apis/python/tools/peek-soco
--- a/apis/python/tools/peek-soco
+++ b/apis/python/tools/peek-soco
@@ -1,35 +1,14 @@
-#!/usr/bin/env python -i
+#!/bin/bash
 
-# Invoke this with, for example,
-#
-#   peek-soco ./soma-collection
-#
-# -- then you can inspect the SOMACollection object
+# Simply runs python -i peek-soco.py.
+# That can be done with '#!/usr/bin/env python -i' in the peek-soco.py shebang
+# line, but not all OSes support three words being present in the shebang line.
+us=$(basename $0)
+ourdir=$(dirname $0)
+py=$ourdir/peek-soco.py
+if [ ! -f $py ]; then
+    echo "$us: cannot find $py" 1>&2
+    exit 1
+fi
 
-import sys
-
-import anndata
-import numpy
-import pandas
-import scipy  # noqa: F401
-import tiledb  # noqa: F401
-
-import tiledbsc
-import tiledbsc.io
-
-# module aliases
-ad = anndata
-np = numpy
-pd = pandas
-
-if len(sys.argv) == 1:
-    soco_path = "soma-collection"
-elif len(sys.argv) == 2:
-    soco_path = sys.argv[1]
-else:
-    print(f"{sys.argv[0]}: need just one soma-collection path.", file=sys.stderr)
-    sys.exit(1)
-
-soco = tiledbsc.SOMACollection(soco_path)
-
-# Interact at the Python prompt now
+exec python -i $py "$@"
diff --git a/apis/python/tools/peek-soma b/apis/python/tools/peek-soma
--- a/apis/python/tools/peek-soma
+++ b/apis/python/tools/peek-soma
@@ -1,47 +1,14 @@
-#!/usr/bin/env python -i
+#!/bin/bash
 
-# Invoke this with, for example,
-#
-#   peek-soma tiledb-data/pbmc3k_processed
-#
-# -- then you can inspect the soma object.
+# Simply runs python -i peek-soma.py.
+# That can be done with '#!/usr/bin/env python -i' in the peek-soma.py shebang
+# line, but not all OSes support three words being present in the shebang line.
+us=$(basename $0)
+ourdir=$(dirname $0)
+py=$ourdir/peek-soma.py
+if [ ! -f $py ]; then
+    echo "$us: cannot find $py" 1>&2
+    exit 1
+fi
 
-import sys
-
-import anndata
-import numpy
-import pandas
-import scipy  # noqa: F401
-import tiledb  # noqa: F401
-
-import tiledbsc
-import tiledbsc.io
-
-# module aliases
-ad = anndata
-np = numpy
-pd = pandas
-
-
-def count_obs(soma: tiledbsc.SOMA, attr_name: str) -> None:
-    print(soma.obs.df(attrs=[attr_name]).groupby(attr_name).size().sort_values())
-
-
-def count_var(soma: tiledbsc.SOMA, attr_name: str) -> None:
-    print(soma.var.df(attrs=[attr_name]).groupby(attr_name).size().sort_values())
-
-
-if len(sys.argv) == 1:
-    input_path = "tiledb-data/pbmc-small"
-    # input_path = 'tiledb-data/pbmc3k_processed'
-elif len(sys.argv) == 2:
-    input_path = sys.argv[1]
-else:
-    print(f"{sys.argv[0]}: need just one soma path.", file=sys.stderr)
-    sys.exit(1)
-
-soma = tiledbsc.SOMA(input_path)
-if not soma.exists():
-    print("Does not exist yet:", input_path)
-
-# Interact at the Python prompt now
+exec python -i $py "$@"
